openapi: "3.0.0"
info:
  version: 1.0.0
  title: Forest api
  license:
    name: MIT
servers:
  - url: http://localhost:3000
paths:
  /tree:
    get:
      summary: List all trees
      operationId: listTrees
      tags:
        - tree
      responses:
        '200':
          description: A tree list was found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Tree"
    post:
      summary: Create a tree
      operationId: createTree
      tags:
        - tree
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Tree"
      responses:
        '201':
          description: Tree created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tree"

  /tree/{id}:
    get:
      summary: Info for a tree
      operationId: getTree
      tags:
        - tree
      parameters:
        - name: id
          in: path
          required: true
          description: The tree id
          schema:
            type: string
      responses:
        '200':
          description: A tree was found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tree"
    put:
      summary: Update a tree
      operationId: updateTree
      tags:
        - tree
      parameters:
        - name: id
          in: path
          required: true
          description: The tree id
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Tree"
      responses:
        '200':
          description: Tree updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tree"
    delete:
      summary: Delete a tree
      operationId: deleteTree
      tags:
        - tree
      parameters:
        - name: id
          in: path
          required: true
          description: The tree id
          schema:
            type: string
      responses:
        '204':
          description: Tree deleted

  /forest:
    get:
      summary: List all forests
      operationId: listForests
      tags:
        - forest
      responses:
        '200':
          description: A forest list was found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Forest"
    post:
      summary: Create a forest
      operationId: createForest
      tags:
        - forest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Forest"
      responses:
        '201':
          description: Forest created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Forest"

  /forest/{id}:
    get:
      summary: Info for a forest
      operationId: getForest
      tags:
        - forest
      parameters:
        - name: id
          in: path
          required: true
          description: The forest id
          schema:
            type: string
      responses:
        '200':
          description: A forest was found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Forest"
    put:
      summary: Update a forest
      operationId: updateForest
      tags:
        - forest
      parameters:
        - name: id
          in: path
          required: true
          description: The forest id
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Forest"
      responses:
        '200':
          description: Forest updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Forest"
    delete:
      summary: Delete a forest
      operationId: deleteForest
      tags:
        - forest
      parameters:
        - name: id
          in: path
          required: true
          description: The forest id
          schema:
            type: string
      responses:
        '204':
          description: Forest deleted
          
  /forest/{id}/species:
    get:
      summary: Get all tree species in a forest
      operationId: getForestTreeSpecies
      tags:
        - forest
      parameters:
        - name: id
          in: path
          required: true
          description: The forest id
          schema:
            type: string
      responses:
        '200':
          description: A list of species was found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /forest/{id}/deforest:
    post:
      summary: Deforest a forest by a given number of trees
      operationId: deforestForest
      tags:
        - forest
      parameters:
        - name: id
          in: path
          required: true
          description: The forest id
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                count:
                  type: integer
      responses:
        '200':
          description: The updated forest
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Forest"
        '400':
          description: Not enough trees to deforest
        '404':
          description: Forest not found

  /co2/forest/{id}/absorption:
    get:
      summary: Get the CO2 absorption of a forest
      operationId: getForestAbsorption
      tags:
        - co2
      parameters:
        - name: id
          in: path
          required: true
          description: The forest id
          schema:
            type: string
      responses:
        '200':
          description: The CO2 absorption of the forest
          content:
            application/json:
              schema:
                type: object
                properties:
                  absorption:
                    type: number
                    format: double
  
  /co2/required-area:
    get:
      summary: Calculate the required forest area to absorb a given amount of CO2
      operationId: getRequiredArea
      tags:
        - co2
      parameters:
        - name: co2Amount
          in: query
          required: true
          description: The amount of CO2 to absorb in kg/year
          schema:
            type: number
            format: double
      responses:
        '200':
          description: The required forest area in hectares
          content:
            application/json:
              schema:
                type: object
                properties:
                  requiredArea:
                    type: number
                    format: double

components:
  schemas:
    Species:
      enum:
        - OAK
        - EVERGREEN_OAK
        - FIR
        - ASH
        - BEECH
    Exposure:
      enum:
        - SUNNY
        - MID_SHADOW
        - SHADOW
    ForestType:
      enum:
        - BOREAL
        - TEMPERATE
        - TROPICAL
    Tree:
      required:
        - id
        - birth
        - species
        - exposure
        - carbonStorageCapacity
      properties:
        id:
          type: string
          format: uuid
        birth:
          type: string
          format: date
        exposure:
          $ref: '#/components/schemas/Exposure'
        species:
          $ref: '#/components/schemas/Species'
        carbonStorageCapacity:
          type: number
          format: double
    Forest:
      required:
        - id
        - type
        - surface
      properties:
        id:
          type: string
          format: uuid
        type:
          $ref: '#/components/schemas/ForestType'
        trees:
          type: array
          items:
            $ref: "#/components/schemas/Tree"
        surface:
          type: number
          format: double
